//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicSubmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collage
    {
        public Collage()
        {
            this.Specializations = new HashSet<Specialization>();
        }
    
        public int Collage_ID { get; set; }
        public string Collage_Name_Ar { get; set; }
        public string Collage_Name_En { get; set; }
    
        public virtual ICollection<Specialization> Specializations { get; set; }
    }
}
