
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ElectronicSubmission
{

using System;
    using System.Collections.Generic;
    
public partial class Resource
{

    public Resource()
    {

        this.Students = new HashSet<Student>();

    }


    public int ResourceID { get; set; }

    public string Resource_Name_Ar { get; set; }

    public string Resource_Name_En { get; set; }



    public virtual ICollection<Student> Students { get; set; }

}

}
