
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ElectronicSubmission
{

using System;
    using System.Collections.Generic;
    
public partial class Student_Other_Info
{

    public int Id { get; set; }

    public Nullable<int> Student_Id { get; set; }

    public string MessageType { get; set; }

    public string Message { get; set; }

    public Nullable<System.DateTime> DateCreation { get; set; }

    public string Note { get; set; }



    public virtual Student Student { get; set; }

}

}
