//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicSubmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Files = new HashSet<File>();
            this.Payment_Process = new HashSet<Payment_Process>();
            this.Sequences = new HashSet<Sequence>();
            this.Student_Other_Info = new HashSet<Student_Other_Info>();
        }
    
        public int Student_Id { get; set; }
        public string Student_SSN { get; set; }
        public string Student_Name_En { get; set; }
        public string Student_Name_Ar { get; set; }
        public string Student_Address { get; set; }
        public string Student_Phone { get; set; }
        public string Student_Email { get; set; }
        public string Student_High_School_Degree { get; set; }
        public string Student_Capabilities_Degree { get; set; }
        public string Student_My_Achievement_Degree { get; set; }
        public Nullable<System.DateTime> Student_CreationDate { get; set; }
        public Nullable<int> Student_Employee_Id { get; set; }
        public Nullable<System.DateTime> Student_Assign_Date { get; set; }
        public string Student_Image_Profile { get; set; }
        public Nullable<int> Student_Specialization_Id { get; set; }
        public Nullable<int> Student_Nationality_Id { get; set; }
        public Nullable<int> Student_Resource_Id { get; set; }
        public Nullable<int> Student_Status_Id { get; set; }
        public string Student_Total { get; set; }
        public Nullable<int> Suspended { get; set; }
        public string Notes { get; set; }
        public string Student_URL_Video { get; set; }
        public Nullable<int> Student_Type_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual ICollection<Payment_Process> Payment_Process { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual ICollection<Sequence> Sequences { get; set; }
        public virtual Specialization Specialization { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<Student_Other_Info> Student_Other_Info { get; set; }
        public virtual Student_Type Student_Type { get; set; }
    }
}
