//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicSubmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Concat
    {
        public int Student_Concat_Id { get; set; }
        public string Student_Concat_Name { get; set; }
        public string Student_Concat_Phone { get; set; }
        public string Student_Concat_Email { get; set; }
        public string Student_Concat_Message { get; set; }
        public Nullable<int> Student_Concat_Status { get; set; }
        public Nullable<System.DateTime> Student_Concat_CreationDate { get; set; }
    
        public virtual Status Status { get; set; }
    }
}
