//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicSubmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Type
    {
        public Student_Type()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Student_Type_Id { get; set; }
        public string Student_Type_Name_Ar { get; set; }
        public string Student_Type_Name_En { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
