//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicSubmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISA_MADA
    {
        public int VISA_MADA_Id { get; set; }
        public Nullable<int> PaymentProcess_Id { get; set; }
        public string Trackingkey { get; set; }
        public string UUID { get; set; }
        public string Result_JSON { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
    
        public virtual Payment_Process Payment_Process { get; set; }
    }
}
